backend:
  name: git-gateway
  repo: buzco/gr8success
  branch: main
  identity_url: https://auth.decapbridge.com/sites/96d7424d-dea8-4b5b-99b2-be63b82feea9
  gateway_url: https://gateway.decapbridge.com
media_folder: "img"                 # path in your repo (relative to root)
public_folder: "/img"              # path seen in HTML

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Image 1"
        name: "image_1"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
        multiple: true
        required: true
        hint: "Update the main picture here"

      - label: "Image 2"
        name: "image_2"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
        multiple: true
        required: true
        hint: "Update the main picture here"
        
      - label: "Image 3"
        name: "image_3"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
        multiple: true
        required: true
        hint: "Update the main picture here"

        
      - label: "Image 4"
        name: "image_4"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
        multiple: true
        required: true
        hint: "Update the main picture here"

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Description"
        name: "description"
        widget: "markdown"
        required: true

      - label: "Size Guide URL"
        name: "size_guide_url"
        widget: "string"
        required: false
        hint: "Paste a link to your size guide (e.g., /size_guide.html)."

      - label: "Shopify Buy Button Embed"
        name: "shopify_embed"
        widget: "text"
        required: true
        hint: "Paste the full Shopify Buy Button `<div>` and `<script>` here."
  
  - name: "archives"
    label: "Archives"
    folder: "srcgi/archive"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"



