backend:
  name: git-gateway
  repo: buzco/gr8success
  branch: main
  identity_url: https://auth.decapbridge.com/sites/96d7424d-dea8-4b5b-99b2-be63b82feea9
  gateway_url: https://gateway.decapbridge.com
media_folder: "img"                 # path in your repo (relative to root)
public_folder: "/img"              # path seen in HTML

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "product-card.njk"
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - label: "Image"
            name: "image"
            widget: "image"
            choose_url: true
        required: true
        hint: "Add one or more product images here"

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Price"
        name: "price"
        widget: "string"
        required: true

      - label: "Description"
        name: "description"
        widget: "markdown"
        required: true

      - label: "Shopify Buy Button Embed"
        name: "shopify_embed"
        widget: "text"
        required: true
        hint: "Paste the full Shopify Buy Button `<div>` and `<script>` here."

      - label: "Product Specifications"
        name: "product_specs"
        widget: "markdown"
        required: true

  - name: "archives"
    label: "Archives"
    folder: "src/archive"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"



